# MCP验证码识别服务器配置文件
server:
  name: "ddddocr-mcp-server"
  version: "1.0.0"
  transport: "stdio"  # stdio 或 sse
  host: "localhost"
  port: 8080

# 验证码识别配置
recognition:
  engine: "ddddocr"
  max_image_size: 5242880  # 5MB
  supported_formats:
    - "png"
    - "jpg"
    - "jpeg"
    - "bmp"
    - "gif"
    - "webp"
  timeout: 30  # 识别超时时间（秒）

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "json"
  file: "logs/mcp_server.log"
  max_size: "10MB"
  backup_count: 5

# 性能配置
performance:
  max_concurrent_requests: 10
  request_timeout: 60
  enable_cache: false